import React from 'react';
import { Footer } from './Footer';
import { PageView } from '../App';

interface PrivacyPolicyPageProps {
  onNavigate?: (page: PageView) => void;
}

export const PrivacyPolicyPage: React.FC<PrivacyPolicyPageProps> = ({ onNavigate }) => {
  return (
    <div className="bg-white min-h-screen font-sans">
      <div className="pt-32 pb-24 md:pt-48 md:pb-32">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          
          {/* Header */}
          <div className="mb-16 border-b border-slate-100 pb-10">
            <h1 className="text-3xl md:text-4xl font-medium tracking-tight text-[#0B1120] mb-4">Privacy Policy</h1>
            <p className="text-slate-500 font-medium">Effective Date: December 17, 2025 &bull; Version: 1.0</p>
          </div>

          {/* Content */}
          <div className="prose prose-slate max-w-none text-slate-600 prose-headings:font-medium prose-headings:text-[#0B1120] prose-h2:text-xl prose-h3:text-lg prose-p:leading-relaxed prose-li:leading-relaxed">
            
            <p>
              CENTURIM SYSTEMS LIMITED ("Centurim," "we," "us," or "our") provides an automated document reconciliation and revenue integrity platform (the "Service"). We are committed to protecting the privacy and security of the data entrusted to us by our commercial clients ("Client," "you," or "your").
            </p>
            <p>
              This Privacy Policy describes how we collect, use, process, and disclose information. By accessing or using the Service, you acknowledge that you have read and understood this Policy.
            </p>

            <div className="my-8 bg-slate-50 border-l-4 border-[#0B1120] p-6 rounded-r-lg">
              <h4 className="text-[#0B1120] font-bold uppercase text-sm mb-2 mt-0">Important Notice Regarding Protected Health Information (PHI)</h4>
              <p className="text-sm mb-0">
                IF YOU ARE A COVERED ENTITY OR BUSINESS ASSOCIATE UNDER HIPAA, YOUR USE OF THE SERVICE IS GOVERNED BY THE BUSINESS ASSOCIATE AGREEMENT (BAA) EXECUTED BETWEEN YOU AND CENTURIM. IN THE EVENT OF A CONFLICT BETWEEN THIS PRIVACY POLICY AND THE BAA, THE TERMS OF THE BAA SHALL CONTROL REGARDING THE HANDLING OF PHI.
              </p>
            </div>

            <h2 id="section-1">1. DEFINITIONS</h2>
            <p>To ensure legal clarity, the following definitions apply:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>"Client Content"</strong> refers to the raw documents, files, PDFs, images, and data payloads uploaded by the Client to the Service for processing (e.g., Hospital Transfer Packets, MDS Assessments, Pay Applications).</li>
              <li><strong>"System Data"</strong> refers to metadata, logs, account information, and usage analytics generated by the Service (e.g., timestamps, job IDs, user login emails).</li>
              <li><strong>"PHI"</strong> refers to Protected Health Information as defined by the Health Insurance Portability and Accountability Act of 1996 ("HIPAA").</li>
              <li><strong>"Ephemeral Processing"</strong> refers to our architectural standard wherein Client Content is processed in volatile memory and permanently deleted from storage immediately upon the completion of the analysis.</li>
            </ul>

            <h2 id="section-2">2. INFORMATION WE COLLECT</h2>
            <p>We collect data in two distinct categories with differing retention standards.</p>
            
            <h3 className="text-[#0B1120] font-medium mt-6">2.1. System Data (Retained)</h3>
            <p>We collect the following information to maintain and bill for the Service:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account Information:</strong> Name, business email address, facility name, and billing details (processed via third-party payment processors; we do not store full credit card numbers).</li>
              <li><strong>Usage Logs:</strong> IP addresses, browser type, operating system, and timestamps of access.</li>
              <li><strong>Job Metadata:</strong> Unique Job IDs (UUIDs), file sizes, processing duration, and error codes. We do not store the filenames of Client Content in our application database if they contain PHI; filenames are anonymized at the ingestion edge.</li>
            </ul>

            <h3 className="text-[#0B1120] font-medium mt-6">2.2. Client Content (Ephemeral)</h3>
            <p>We process Client Content solely for the purpose of generating Variance Reports.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Ingestion:</strong> Client Content is uploaded directly to our secure storage enclave via presigned cryptographic URLs.</li>
              <li><strong>Processing:</strong> Content is analyzed by our automated logic engines.</li>
              <li><strong>Deletion:</strong> Client Content is not retained. Upon the generation of the output report, the source files are logically and physically marked for deletion in accordance with our Data Lifecycle Policy. We do not use Client Content to train foundational artificial intelligence models.</li>
            </ul>

            <h2 id="section-3">3. HOW WE USE INFORMATION</h2>
            <p>We use the information collected for the following specific business purposes:</p>
            <ol className="list-decimal pl-5 space-y-2">
              <li><strong>To Provide the Service:</strong> To authenticate users, process uploaded documents, and deliver variance reports.</li>
              <li><strong>To Maintain Security:</strong> To monitor for unauthorized access, suspicious activity, and potential breaches (e.g., AWS CloudTrail logging).</li>
              <li><strong>To Communicate:</strong> To send transactional emails (e.g., "Audit Complete," "Invoice Available") and critical security alerts.</li>
              <li><strong>To Comply with Law:</strong> To satisfy tax, legal, and regulatory requirements.</li>
            </ol>
            <p className="font-bold text-[#0B1120] mt-4">WE DO NOT SELL YOUR DATA. We do not share Client Content with third parties for marketing purposes. We do not monetize your data.</p>

            <h2 id="section-4">4. HIPAA COMPLIANCE & PROTECTED HEALTH INFORMATION (PHI)</h2>
            
            <h3 className="text-[#0B1120] font-medium mt-6">4.1. Business Associate Status</h3>
            <p>When processing Client Content containing PHI on behalf of a Covered Entity, Centurim acts as a Business Associate under HIPAA. We adhere to the Security Rule and Privacy Rule requirements applicable to Business Associates.</p>

            <h3 className="text-[#0B1120] font-medium mt-6">4.2. The Business Associate Agreement (BAA)</h3>
            <p>Our obligations regarding PHI are strictly defined in the BAA. The BAA supersedes this Privacy Policy regarding the handling, breach notification, and liability of PHI. If you have not executed a BAA with Centurim, you are strictly prohibited from uploading PHI to the Service.</p>

            <h3 className="text-[#0B1120] font-medium mt-6">4.3. Minimum Necessary Standard</h3>
            <p>Our automated systems are architected to extract only the data points necessary to perform the reconciliation audit (e.g., specific diagnoses, functional scores). We do not aggregate or mine PHI for secondary purposes.</p>

            <h2 id="section-5">5. DATA SOVEREIGNTY & INTERNATIONAL TRANSFERS</h2>
            
            <h3 className="text-[#0B1120] font-medium mt-6">5.1. United States Residency</h3>
            <p>Centurim guarantees that all Client Content is processed and stored exclusively within the United States.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Infrastructure:</strong> Our primary processing nodes are located in the AWS US-East-1 (Northern Virginia) data center region.</li>
              <li><strong>No Export:</strong> We do not replicate, backup, or transfer Client Content to servers outside the territorial United States.</li>
            </ul>

            <h3 className="text-[#0B1120] font-medium mt-6">5.2. Global Operations & Access</h3>
            <p>While data storage is sovereign to the US, Centurim utilizes a global technical team for system maintenance and security monitoring.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Remote Access Protocol:</strong> Any administrative access to the US production environment by non-US personnel is conducted via secure, encrypted Virtual Private Network (VPN) tunnels and Virtual Desktop Infrastructure (VDI).</li>
              <li><strong>No Local Storage:</strong> Non-US personnel are technically restricted from downloading Client Content to local devices. All data remains within the US cloud enclave during maintenance operations.</li>
            </ul>

            <h2 id="section-6">6. SECURITY ARCHITECTURE</h2>
            <p>We implement defense-in-depth security measures aligned with NIST 800-66 guidelines.</p>
            
            <h3 className="text-[#0B1120] font-medium mt-6">6.1. Encryption</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Data at Rest:</strong> All Client Content is encrypted using AES-256 (Advanced Encryption Standard) via Server-Side Encryption with AWS Key Management Service (SSE-KMS).</li>
              <li><strong>Data in Transit:</strong> All data transmission occurs over TLS 1.3 (Transport Layer Security) encrypted channels. We enforce HTTPS Strict Transport Security (HSTS).</li>
            </ul>

            <h3 className="text-[#0B1120] font-medium mt-6">6.2. Access Control</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Least Privilege:</strong> System components operate with the minimum permissions necessary.</li>
              <li><strong>Multi-Factor Authentication (MFA):</strong> Administrative access to our cloud infrastructure requires hardware-based or app-based MFA.</li>
              <li><strong>Audit Logging:</strong> We maintain immutable logs of all system access, file uploads, and processing events via AWS CloudTrail. These logs are retained for a minimum of six (6) years.</li>
            </ul>

            <h3 className="text-[#0B1120] font-medium mt-6">6.3. Vulnerability Management</h3>
            <p>We conduct regular automated vulnerability scans of our infrastructure. We utilize automated patch management to ensure all serverless runtimes are up to date.</p>

            <h2 id="section-7">7. DATA RETENTION & DELETION</h2>
            
            <h3 className="text-[#0B1120] font-medium mt-6">7.1. Ephemeral Processing Policy</h3>
            <p>Centurim operates on a strict Zero-Retention basis for Client Content.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Source Files:</strong> Original documents (PDFs) uploaded by the Client are automatically scheduled for permanent deletion immediately upon the successful generation of the Variance Report.</li>
              <li><strong>Output Reports:</strong> Generated Variance Reports are retained in secure storage for a period of seven (7) days to allow for Client download. After this period, they are permanently deleted.</li>
              <li><strong>Backup Policy:</strong> We do not perform long-term archival backups of Client Content. Once deleted, data is unrecoverable.</li>
            </ul>

            <h3 className="text-[#0B1120] font-medium mt-6">7.2. System Data Retention</h3>
            <p>We retain System Data (logs, billing history, account metadata) for as long as your account is active or as needed to comply with legal obligations, resolve disputes, and enforce our agreements.</p>

            <h2 id="section-8">8. CLIENT RESPONSIBILITIES</h2>
            <p>You acknowledge and agree that you are solely responsible for:</p>
            <ol className="list-decimal pl-5 space-y-2">
              <li><strong>Data Hygiene:</strong> Ensuring that you have the legal right and patient consent (where applicable) to upload Client Content to the Service.</li>
              <li><strong>Redaction:</strong> Unless a BAA is executed, you must redact all direct identifiers (Name, SSN, MRN) before upload.</li>
              <li><strong>Access Management:</strong> Protecting your account credentials. You are responsible for all activity that occurs under your account.</li>
              <li><strong>Verification:</strong> The Service provides automated data analysis, not professional advice. You must independently verify all findings, variances, and reports against the original source documentation before making any billing, clinical, or legal decisions.</li>
            </ol>

            <h2 id="section-9">9. DISCLAIMERS & LIMITATION OF LIABILITY</h2>
            
            <h3 className="text-[#0B1120] font-medium mt-6">9.1. No Medical or Legal Advice</h3>
            <p>THE SERVICE IS A DATA PROCESSING TOOL. CENTURIM DOES NOT PRACTICE MEDICINE, LAW, OR ACCOUNTING. THE OUTPUT OF THE SERVICE DOES NOT CONSTITUTE MEDICAL DIAGNOSIS, LEGAL COUNSEL, OR A GUARANTEE OF REIMBURSEMENT.</p>

            <h3 className="text-[#0B1120] font-medium mt-6">9.2. "As Is" Basis</h3>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>

            <h2 id="section-10">10. JURISDICTION & DISPUTE RESOLUTION</h2>
            
            <h3 className="text-[#0B1120] font-medium mt-6">10.1. Governing Law</h3>
            <p>This Privacy Policy and any disputes arising out of or related to it shall be governed by and construed in accordance with the laws of the Commonwealth of Virginia, United States, without regard to its conflict of law principles.</p>

            <h3 className="text-[#0B1120] font-medium mt-6">10.2. Venue</h3>
            <p>You agree to submit to the exclusive personal jurisdiction of the state and federal courts located in Richmond, Virginia, for the resolution of any disputes.</p>

            <h2 id="section-11">11. CHANGES TO THIS POLICY</h2>
            <p>We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or by posting a notice in the Service prior to the effective date of the changes. Your continued use of the Service after the effective date constitutes your acceptance of the amended Policy.</p>

            <h2 id="section-12">12. CONTACT INFORMATION</h2>
            <p>If you have questions about this Privacy Policy or our privacy practices, please contact our Privacy Officer:</p>
            <div className="bg-slate-50 p-6 rounded-lg border border-slate-200 mt-4 not-prose">
              <p className="font-bold text-[#0B1120]">Centurim Systems Limited</p>
              <p className="text-slate-600">Attn: Privacy Officer</p>
              <p className="text-slate-600">Email: <a href="mailto:contact@centurim.com" className="text-[#2563EB] hover:underline">contact@centurim.com</a></p>
              <div className="mt-4 pt-4 border-t border-slate-200">
                <p className="text-slate-900 font-medium mb-1">USA Address</p>
                <p className="text-slate-600">701 E Franklin Street, Suite 105<br/>Richmond, VA 23219, United States</p>
              </div>
              <div className="mt-4 pt-4 border-t border-slate-200">
                <p className="text-slate-900 font-medium mb-1">UK Address</p>
                <p className="text-slate-600">71-75 Shelton Street, Covent Garden<br/>London, WC2H 9JQ</p>
              </div>
            </div>

          </div>
        </div>
      </div>
      <Footer onNavigate={onNavigate} />
    </div>
  );
};