import React from 'react';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="bg-white min-h-screen py-16 md:py-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">PRIVACY POLICY</h1>
        <div className="text-sm text-slate-500 mb-8 border-b border-slate-200 pb-8">
            <p>Effective Date: December 511, 2025</p>
            <p>Version: 1.0</p>
        </div>
        
        <div className="prose prose-slate max-w-none text-slate-600 space-y-8">
            <p>
                CENTURIM SYSTEMS LIMITED ("Centurim," "we," "us," or "our") provides an automated document reconciliation and revenue integrity platform (the "Service"). We are committed to protecting the privacy and security of the data entrusted to us by our commercial clients ("Client," "you," or "your").
            </p>
            <p>
                This Privacy Policy describes how we collect, use, process, and disclose information. By accessing or using the Service, you acknowledge that you have read and understood this Policy.
            </p>
            
            <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 border-l-4 border-l-slate-900">
                <p className="text-xs font-bold text-slate-900 uppercase tracking-widest mb-2">IMPORTANT NOTICE REGARDING PROTECTED HEALTH INFORMATION (PHI):</p>
                <p className="text-sm text-slate-700 font-medium leading-relaxed">
                    IF YOU ARE A COVERED ENTITY OR BUSINESS ASSOCIATE UNDER HIPAA, YOUR USE OF THE SERVICE IS GOVERNED BY THE BUSINESS ASSOCIATE AGREEMENT (BAA) EXECUTED BETWEEN YOU AND CENTURIM. IN THE EVENT OF A CONFLICT BETWEEN THIS PRIVACY POLICY AND THE BAA, THE TERMS OF THE BAA SHALL CONTROL REGARDING THE HANDLING OF PHI.
                </p>
            </div>

            {/* Section 1 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">1. DEFINITIONS</h2>
                <p className="mb-4">To ensure legal clarity, the following definitions apply:</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">"Client Content"</strong> refers to the raw documents, files, PDFs, images, and data payloads uploaded by the Client to the Service for processing (e.g., Hospital Transfer Packets, MDS Assessments, Pay Applications).</li>
                    <li><strong className="text-slate-900">"System Data"</strong> refers to metadata, logs, account information, and usage analytics generated by the Service (e.g., timestamps, job IDs, user login emails).</li>
                    <li><strong className="text-slate-900">"PHI"</strong> refers to Protected Health Information as defined by the Health Insurance Portability and Accountability Act of 1996 ("HIPAA").</li>
                    <li><strong className="text-slate-900">"Ephemeral Processing"</strong> refers to our architectural standard wherein Client Content is processed in volatile memory and permanently deleted from storage immediately upon the completion of the analysis.</li>
                </ul>
            </section>

             {/* Section 2 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">2. INFORMATION WE COLLECT</h2>
                <p className="mb-4">We collect data in two distinct categories with differing retention standards.</p>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">2.1. System Data (Retained)</h3>
                <p className="mb-4">We collect the following information to maintain and bill for the Service:</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Account Information:</strong> Name, business email address, facility name, and billing details (processed via third-party payment processors; we do not store full credit card numbers).</li>
                    <li><strong className="text-slate-900">Usage Logs:</strong> IP addresses, browser type, operating system, and timestamps of access.</li>
                    <li><strong className="text-slate-900">Job Metadata:</strong> Unique Job IDs (UUIDs), file sizes, processing duration, and error codes. We do not store the filenames of Client Content in our application database if they contain PHI; filenames are anonymized at the ingestion edge.</li>
                </ul>

                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">2.2. Client Content (Ephemeral)</h3>
                <p className="mb-4">We process Client Content solely for the purpose of generating Variance Reports.</p>
                 <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Ingestion:</strong> Client Content is uploaded directly to our secure storage enclave via presigned cryptographic URLs.</li>
                    <li><strong className="text-slate-900">Processing:</strong> Content is analyzed by our automated logic engines.</li>
                    <li><strong className="text-slate-900">Deletion:</strong> Client Content is not retained. Upon the generation of the output report, the source files are logically and physically marked for deletion in accordance with our Data Lifecycle Policy. We do not use Client Content to train foundational artificial intelligence models.</li>
                </ul>
            </section>

             {/* Section 3 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">3. HOW WE USE INFORMATION</h2>
                <p className="mb-4">We use the information collected for the following specific business purposes:</p>
                <ol className="list-decimal pl-5 space-y-2">
                    <li><strong className="text-slate-900">To Provide the Service:</strong> To authenticate users, process uploaded documents, and deliver variance reports.</li>
                    <li><strong className="text-slate-900">To Maintain Security:</strong> To monitor for unauthorized access, suspicious activity, and potential breaches (e.g., AWS CloudTrail logging).</li>
                    <li><strong className="text-slate-900">To Communicate:</strong> To send transactional emails (e.g., "Audit Complete," "Invoice Available") and critical security alerts.</li>
                    <li><strong className="text-slate-900">To Comply with Law:</strong> To satisfy tax, legal, and regulatory requirements.</li>
                </ol>
                <p className="mt-4 font-bold text-slate-900">WE DO NOT SELL YOUR DATA. We do not share Client Content with third parties for marketing purposes. We do not monetize your data.</p>
            </section>

            {/* Section 4 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">4. HIPAA COMPLIANCE & PROTECTED HEALTH INFORMATION (PHI)</h2>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">4.1. Business Associate Status</h3>
                <p className="mb-4">When processing Client Content containing PHI on behalf of a Covered Entity, Centurim acts as a Business Associate under HIPAA. We adhere to the Security Rule and Privacy Rule requirements applicable to Business Associates.</p>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">4.2. The Business Associate Agreement (BAA)</h3>
                <p className="mb-4">Our obligations regarding PHI are strictly defined in the BAA. The BAA supersedes this Privacy Policy regarding the handling, breach notification, and liability of PHI. If you have not executed a BAA with Centurim, you are strictly prohibited from uploading PHI to the Service.</p>

                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">4.3. Minimum Necessary Standard</h3>
                <p className="mb-4">Our automated systems are architected to extract only the data points necessary to perform the reconciliation audit (e.g., specific diagnoses, functional scores). We do not aggregate or mine PHI for secondary purposes.</p>
            </section>

            {/* Section 5 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">5. DATA SOVEREIGNTY & INTERNATIONAL TRANSFERS</h2>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">5.1. United States Residency</h3>
                <p className="mb-4">Centurim guarantees that all Client Content is processed and stored exclusively within the United States.</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Infrastructure:</strong> Our primary processing nodes are located in the AWS US-East-1 (Northern Virginia) data center region.</li>
                    <li><strong className="text-slate-900">No Export:</strong> We do not replicate, backup, or transfer Client Content to servers outside the territorial United States.</li>
                </ul>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">5.2. Global Operations & Access</h3>
                <p className="mb-4">While data storage is sovereign to the US, Centurim utilizes a global technical team for system maintenance and security monitoring.</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Remote Access Protocol:</strong> Any administrative access to the US production environment by non-US personnel is conducted via secure, encrypted Virtual Private Network (VPN) tunnels and Virtual Desktop Infrastructure (VDI).</li>
                    <li><strong className="text-slate-900">No Local Storage:</strong> Non-US personnel are technically restricted from downloading Client Content to local devices. All data remains within the US cloud enclave during maintenance operations.</li>
                </ul>
            </section>

             {/* Section 6 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">6. SECURITY ARCHITECTURE</h2>
                <p className="mb-4">We implement defense-in-depth security measures aligned with NIST 800-66 guidelines.</p>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">6.1. Encryption</h3>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Data at Rest:</strong> All Client Content is encrypted using AES-256 (Advanced Encryption Standard) via Server-Side Encryption with AWS Key Management Service (SSE-KMS).</li>
                    <li><strong className="text-slate-900">Data in Transit:</strong> All data transmission occurs over TLS 1.3 (Transport Layer Security) encrypted channels. We enforce HTTPS Strict Transport Security (HSTS).</li>
                </ul>

                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">6.2. Access Control</h3>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Least Privilege:</strong> System components operate with the minimum permissions necessary.</li>
                    <li><strong className="text-slate-900">Multi-Factor Authentication (MFA):</strong> Administrative access to our cloud infrastructure requires hardware-based or app-based MFA.</li>
                    <li><strong className="text-slate-900">Audit Logging:</strong> We maintain immutable logs of all system access, file uploads, and processing events via AWS CloudTrail. These logs are retained for a minimum of six (6) years.</li>
                </ul>

                 <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">6.3. Vulnerability Management</h3>
                 <p className="mb-4">We conduct regular automated vulnerability scans of our infrastructure. We utilize automated patch management to ensure all serverless runtimes are up to date.</p>
            </section>

            {/* Section 7 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">7. DATA RETENTION & DELETION</h2>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">7.1. Ephemeral Processing Policy</h3>
                <p className="mb-4">Centurim operates on a strict Zero-Retention basis for Client Content.</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong className="text-slate-900">Source Files:</strong> Original documents (PDFs) uploaded by the Client are automatically scheduled for permanent deletion immediately upon the successful generation of the Variance Report.</li>
                    <li><strong className="text-slate-900">Output Reports:</strong> Generated Variance Reports are retained in secure storage for a period of seven (7) days to allow for Client download. After this period, they are permanently deleted.</li>
                    <li><strong className="text-slate-900">Backup Policy:</strong> We do not perform long-term archival backups of Client Content. Once deleted, data is unrecoverable.</li>
                </ul>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">7.2. System Data Retention</h3>
                <p className="mb-4">We retain System Data (logs, billing history, account metadata) for as long as your account is active or as needed to comply with legal obligations, resolve disputes, and enforce our agreements.</p>
            </section>

             {/* Section 8 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">8. CLIENT RESPONSIBILITIES</h2>
                <p className="mb-4">You acknowledge and agree that you are solely responsible for:</p>
                <ol className="list-decimal pl-5 space-y-2">
                    <li><strong className="text-slate-900">Data Hygiene:</strong> Ensuring that you have the legal right and patient consent (where applicable) to upload Client Content to the Service.</li>
                    <li><strong className="text-slate-900">Redaction:</strong> Unless a BAA is executed, you must redact all direct identifiers (Name, SSN, MRN) before upload.</li>
                    <li><strong className="text-slate-900">Access Management:</strong> Protecting your account credentials. You are responsible for all activity that occurs under your account.</li>
                    <li><strong className="text-slate-900">Verification:</strong> The Service provides automated data analysis, not professional advice. You must independently verify all findings, variances, and reports against the original source documentation before making any billing, clinical, or legal decisions.</li>
                </ol>
            </section>

             {/* Section 9 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">9. DISCLAIMERS & LIMITATION OF LIABILITY</h2>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">9.1. No Medical or Legal Advice</h3>
                <p className="mb-4 uppercase font-medium">THE SERVICE IS A DATA PROCESSING TOOL. CENTURIM DOES NOT PRACTICE MEDICINE, LAW, OR ACCOUNTING. THE OUTPUT OF THE SERVICE DOES NOT CONSTITUTE MEDICAL DIAGNOSIS, LEGAL COUNSEL, OR A GUARANTEE OF REIMBURSEMENT.</p>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">9.2. "As Is" Basis</h3>
                <p className="mb-4 uppercase font-medium">TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
            </section>

            {/* Section 10 */}
            <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">10. JURISDICTION & DISPUTE RESOLUTION</h2>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">10.1. Governing Law</h3>
                <p className="mb-4">This Privacy Policy and any disputes arising out of or related to it shall be governed by and construed in accordance with the laws of the Commonwealth of Virginia, United States, without regard to its conflict of law principles.</p>
                
                <h3 className="text-lg font-bold text-slate-900 mb-2 mt-6">10.2. Venue</h3>
                <p className="mb-4">You agree to submit to the exclusive personal jurisdiction of the state and federal courts located in Richmond, Virginia, for the resolution of any disputes.</p>
            </section>

             {/* Section 11 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">11. CHANGES TO THIS POLICY</h2>
                <p className="mb-4">We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or by posting a notice in the Service prior to the effective date of the changes. Your continued use of the Service after the effective date constitutes your acceptance of the amended Policy.</p>
            </section>

             {/* Section 12 */}
             <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4">12. CONTACT INFORMATION</h2>
                <p className="mb-4">If you have questions about this Privacy Policy or our privacy practices, please contact our Privacy Officer:</p>
                <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                    <p className="font-bold text-slate-900">Centurim Systems Limited</p>
                    <p className="text-slate-600">Attn: Privacy Officer</p>
                    <p className="text-slate-600">Email: <a href="mailto:contact@centurim.com" className="text-medical-600 hover:underline">contact@centurim.com</a></p>
                    <p className="text-slate-600 mt-2">USA Address: 701 E Franklin Street, Suite 105, Richmond, VA 23219, United States</p>
                    <p className="text-slate-600">UK Address - 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ</p>
                </div>
            </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;